### ISSUE TITLE
Tournament returned by endpoints "known" and "open" are already finished

### ISSUE THREAD

**Issue by Tithanium** [RoyaleAPI/cr-api#281]
1) All the trounament tags retreived by the endpoints tournaments/known and tournaments/open are refering to ended tournaments.
2) Once this is fixed, would it be possible to have more than 100 tournements in the list ?
Thks !!
Tithan

**Comment by fourjr** [comment]
this isn't a bug tho

**Comment by Tithanium** [comment]
Nop, but it makes the endpoint useless...Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [RoyaleAPI/cr-api] Tournament returned by endpoints "known" and "open" are already finished (#281)De : fourjr À : RoyaleAPI/cr-api Cc : Tithanium ,Author this isn't a bug tho

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RoyaleAPI/cr-api","title":"RoyaleAPI/cr-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RoyaleAPI/cr-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fourjr in #281: this isn't a bug tho"}],"action":{"name":"View Issue","url":"https://github.com/RoyaleAPI/cr-api/issues/281#issuecomment-373919046"}}}

**Comment by fourjr** [comment]
you can filter it in hour own program

**Comment by Tithanium** [comment]
Nop because I get only 100 clan tag.. and what can i do if none remain
after filtering?

**Comment by selfish** [comment]
Fixed in version `v10.6.14`

**Comment by Tithanium** [comment]
Thanks ! I just checked but have still the same issue: the tournaments are supposed to be in Preparation but are in fact ended...Envoyé depuis mon mobile Huawei-------- Message original --------Objet : Re: [RoyaleAPI/cr-api] Tournament returned by endpoints "known" and "open" are already finished (#281)De : selfish À : RoyaleAPI/cr-api Cc : Tithanium ,Author Fixed in version v10.6.14

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/RoyaleAPI/cr-api","title":"RoyaleAPI/cr-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/RoyaleAPI/cr-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@selfish in #281: Fixed in version `v10.6.14`"}],"action":{"name":"View Issue","url":"https://github.com/RoyaleAPI/cr-api/issues/281#issuecomment-374067468"}}}
